AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance, Elastic IP, and S3 bucket

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - test
      - stage
      - prod

Conditions:
  CreateProdResources: !Equals [!Ref Environment, prod ]

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref EC2SecurityGroup
      ImageId:  "ami-0c55b159cbfafe1f0"  

  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateProdResources
    Properties:
      BucketName: mybucket  
      AccessControl: Private   

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access 
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'      
        - CidrIp: 0.0.0.0/0
          FromPort: '80'
          IpProtocol: tcp
          ToPort: '80'
